### PR TITLE
Add test suite effects order

### PR DESCRIPTION
**Pull request by TimvdLippe**
Adds a test suite for testing the effects order

### CODE REVIEW

**Comment by kaste** [comment]
Wow. I wonder why this works. I thought upwards notifications are event
based and thus always unordered.

Tim van der Lippe notifications@github.com schrieb am Fr., 5. Feb. 2016
15:44:

**Comment by TimvdLippe** [comment]
Nope, they are instantaneously propagated.

**Comment by kaste** [comment]
Really like the test, changed it here https://github.com/kaste/polymer/commit/db7c32491cecf8fbbbfba21cd395125801a02e11 so that it looks more like a spec and provides some documentation.

I like the test b/c it shows clearly that for example verifying a property in the (simple) observer is way too late (as someone suggested in one of the issues). 

It shows also that although technically 'ordered' as defined, you can barely speak of a defined (and in that sense ordered) flow of data through the system. I find it very interesting to see that Polymer switches the subject/the current actor from the element-under-test to child to grand-parent back to element-under-test. 

It seems like it wants to pass the data down as fast as possible. But the effect here is that the side effects (observers) of children run before its parent settled.

**Comment by kaste** [comment]
Seems like the @googlebot wants you to confirm (in the original PR) that your code can be contributed to Google code. https://github.com/Polymer/polymer/pull/3354#issuecomment-180600327

**Pull request merged**
